version: "3.9"

services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      # References the TOKEN variable from the .env file
      - TUNNEL_TOKEN=${TOKEN}